#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
# 	   curl http://35.229.54.225/   --> returns string "Hello World!"
#	   curl http://35.229.54.225/   --> returns header info
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx start
